<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHPUnit_Runner_Exception" namespace="" name="PHPUnit_Runner_Exception" abstract="false" final="false" start="14" end="16">
  <file path="/home/web/example/src/freegame_developer/vendor/phpunit/phpunit/src/Runner" file="Exception.php" realpath="/home/web/example/src/freegame_developer/vendor/phpunit/phpunit/src/Runner/Exception.php" size="372" time="2016-02-11T14:56:33+00:00" unixtime="1455202593" sha1="0cdd44e3baeafa1a48f16a53c50070c24f04bbf5" relative="freegame_developer/vendor/phpunit/phpunit/src/Runner/Exception.php"/>
  <docblock>
    <description/>
    <since value="Class available since Release 4.0.0"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
  <implements full="PHPUnit_Exception" namespace="" name="PHPUnit_Exception"/>
</class>
