<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="PHPUnit_Framework_MockObject_RuntimeException" namespace="" name="PHPUnit_Framework_MockObject_RuntimeException" abstract="false" final="false" start="14" end="16">
  <file path="/home/web/example/src/freegame_developer/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Exception" file="RuntimeException.php" realpath="/home/web/example/src/freegame_developer/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Exception/RuntimeException.php" size="437" time="2015-10-02T06:51:40+00:00" unixtime="1443768700" sha1="4d9e47e8c3fb05201f4a483ea1aa4adad34df8a7" relative="freegame_developer/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Exception/RuntimeException.php"/>
  <docblock>
    <description/>
    <since value="Class available since Release 2.0.6"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
  <implements full="PHPUnit_Framework_MockObject_Exception" namespace="" name="PHPUnit_Framework_MockObject_Exception"/>
</class>
