<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpKernel\Exception\BadRequestHttpException" namespace="Symfony\Component\HttpKernel\Exception" name="BadRequestHttpException" abstract="false" final="false" start="19" end="32">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/http-kernel/Exception" file="BadRequestHttpException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/http-kernel/Exception/BadRequestHttpException.php" size="828" time="2016-10-27T01:37:19+00:00" unixtime="1477532239" sha1="0ae4bf0e3a72786208278ecb04cb3340751de31d" relative="freegame_developer/vendor/symfony/http-kernel/Exception/BadRequestHttpException.php"/>
  <docblock>
    <description compact="BadRequestHttpException."/>
    <author value="Ben Ramsey &lt;ben@benramsey.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\HttpKernel\Exception\HttpException" namespace="Symfony\Component\HttpKernel\Exception" name="HttpException"/>
  <constructor name="__construct" start="28" end="31" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Constructor."/>
      <param description="The internal exception message" type="string" variable="$message"/>
      <param description="The previous exception" type="object" variable="$previous">
        <type full="\Exception" namespace="" name="Exception"/>
      </param>
      <param description="The internal exception code" type="int" variable="$code"/>
    </docblock>
    <parameter name="message" byreference="false" type="{unknown}" default="" constant="null"/>
    <parameter name="previous" byreference="false" type="{unknown}" default="" constant="null">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
    <parameter name="code" byreference="false" type="integer" default="0"/>
  </constructor>
</class>
