<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Process\Exception\LogicException" namespace="Symfony\Component\Process\Exception" name="LogicException" abstract="false" final="false" start="19" end="21">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/process/Exception" file="LogicException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/process/Exception/LogicException.php" size="466" time="2016-09-29T02:20:21+00:00" unixtime="1475115621" sha1="b98331d61ea70e49b2fb67fa94c63ebe5a7c61c3" relative="freegame_developer/vendor/symfony/process/Exception/LogicException.php"/>
  <docblock>
    <description compact="LogicException for the Process Component."/>
    <author value="Romain Neutron &lt;imprec@gmail.com&gt;"/>
  </docblock>
  <extends full="LogicException" namespace="" name="LogicException"/>
  <implements full="Symfony\Component\Process\Exception\ExceptionInterface" namespace="Symfony\Component\Process\Exception" name="ExceptionInterface"/>
</class>
